import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService {
  static const String _languageKey = 'app_language';
  static String _currentLanguage = 'English';

  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'appName': 'CocoScan',
      'home': 'Home',
      'scan': 'Scan',
      'drone': 'Drone',
      'history': 'History',
      'profile': 'Profile',
      'myProfile': 'My Profile',
      'editProfile': 'Edit Profile',
      'goodMorning': 'Good Morning',
      'goodAfternoon': 'Good Afternoon',
      'goodEvening': 'Good Evening',
      'scansToday': 'Scans Today',
      'diseasesFound': 'Diseases Found',
      'treeHealth': 'Tree Health',
      'plantationHealthReport': 'Plantation Health Report',
      'treesMonitored': 'trees monitored this week',
      'healthy': 'Healthy',
      'needAttention': 'need attention',
      'quickActions': 'Quick Actions',
      'scanLeaf': 'Scan Leaf',
      'takePhoto': 'Take a photo',
      'droneReport': 'Drone Report',
      'uploadFootage': 'Upload footage',
      'scanHistory': 'Scan History',
      'pastResults': 'Past results',
      'analytics': 'Analytics',
      'diseaseTrends': 'Disease trends',
      'diseaseOverview': 'Disease Overview',
      'thisMonth': 'This Month',
      'recentAlerts': 'Recent Alerts',
      'quickScan': 'Quick Scan',
      'settings': 'Settings',
      'notifications': 'Notifications',
      'darkMode': 'Dark Mode',
      'autoSync': 'Auto Sync',
      'locationTracking': 'Location Tracking',
      'language': 'Language',
      'storageUsed': 'Storage Used',
      'appVersion': 'App Version',
      'help': 'Help & FAQ',
      'logout': 'Logout',
      'deleteAccount': 'Delete Account',
      'selectLanguage': 'Select Language',
      'profileImageUpdated': 'Profile image uploaded successfully.',
      'failedToUploadImage': 'Failed to upload profile image',
      'leafSpot': 'Leaf Spot',
      'lethalYellowing': 'Lethal Yellowing',
      'budRot': 'Bud Rot',
      'confirmed': 'CONFIRMED',
      'uncertain': 'UNCERTAIN',
      'seeAll': 'See All',
    },
    'Sinhala': {
      'appName': 'කොකෝස්කෑන්',
      'home': 'ගෙවතින්න',
      'scan': 'පරිசරණය කරන්න',
      'drone': 'ඩ්‍රෝන්',
      'history': 'ඉතිහාසය',
      'profile': 'පැතිකඩ',
      'myProfile': 'මගේ පැතිකඩ',
      'editProfile': 'පැතිකඩ සංස්කරණය කරන්න',
      'goodMorning': 'සුබ උදෑසනක්',
      'goodAfternoon': 'සුබ දහවල්',
      'goodEvening': 'සුබ සවස්',
      'scansToday': 'අද පරිසරණ',
      'diseasesFound': 'සිතුවම් සොයා ගනු ලැබුණ',
      'treeHealth': 'ගස් සෞක්ය',
      'plantationHealthReport': 'වතු සෞක්ය වාර්තා',
      'treesMonitored': 'ගස් මෙම සතියේ නිරීක්ෂණය කරන ලද',
      'healthy': 'සෞවර්ය',
      'needAttention': 'අවධානය ඉල්ලා සිටින්න',
      'quickActions': 'ඉතා ද්‍රුත ක්‍රියා',
      'scanLeaf': 'පත්‍ර පරිසරණය කරන්න',
      'takePhoto': 'ඡායාරූපයක් ගන්න',
      'droneReport': 'ඩ්‍රෝන් වාර්තා',
      'uploadFootage': 'පටිගත කිරීම උඩුගත කරන්න',
      'scanHistory': 'පරිසරණ ඉතිහාසය',
      'pastResults': 'පෙර ප්‍රතිඵල',
      'analytics': 'විශ්ලේෂණ',
      'diseaseTrends': 'රෝග ප්‍රවර්තන',
      'diseaseOverview': 'රෝග දළ විශ්ලේෂණ',
      'thisMonth': 'මෙම මසින්',
      'recentAlerts': 'මෑතකාලීන සতර්කතා',
      'quickScan': 'ඉතා ද්‍රුත පරිසරණය',
      'settings': 'සැකසුම්',
      'notifications': 'නිවේදනය',
      'darkMode': 'අඳුරු ප්‍රකාරය',
      'autoSync': 'ස්වයංක්‍රිය සම්මතීකරණ',
      'locationTracking': 'පිහිටීම් ට්‍රැකින්',
      'language': 'භාෂාව',
      'storageUsed': 'භාවිතා කරන ලද ගබඩාව',
      'appVersion': 'යෙදුම් සংස්කරණය',
      'help': 'උදව් සහ සිතින්න විමසුම්',
      'logout': 'ඉවත් වන්න',
      'deleteAccount': 'ගිණුම මකා දමන්න',
      'selectLanguage': 'භාෂාව තෝරන්න',
      'profileImageUpdated': 'පැතිකඩ ඡායාරූපය සফලව උඩුගත කරන ලද.',
      'failedToUploadImage': 'පැතිකඩ ඡායාරූපය උඩුගත කිරීමට අපොහොසත් විය',
      'leafSpot': 'පත්‍ර කළුවර',
      'lethalYellowing': 'මරණ දරවි',
      'budRot': 'අංකුරු腐',
      'confirmed': 'තහවුරු කරන ලද',
      'uncertain': 'නිශ්චිතවි නොවන',
      'seeAll': 'සියල්ල බලන්න',
    },
    'Tamil': {
      'appName': 'CocoScan',
      'home': 'முகப்பு',
      'scan': 'ஸ்கேன் செய்',
      'drone': 'ড্রোন',
      'history': 'வரலாறு',
      'profile': 'சுயவிவரம்',
      'myProfile': 'என் சுயவிவரம்',
      'editProfile': 'சுயவிவரத்தை திருத்து',
      'goodMorning': 'நல்ல காலை',
      'goodAfternoon': 'நல்ல பிற்பகல்',
      'goodEvening': 'நல்ல மாலை',
      'scansToday': 'இன்றைய ஸ்கேன்',
      'diseasesFound': 'நோய்கள் கண்டுபிடிக்கப்பட்டன',
      'treeHealth': 'மரத்தின் ஆரோக்கியம்',
      'plantationHealthReport': 'தோட்ட ஆரோக்கிய அறிக்கை',
      'treesMonitored': 'இந்த வாரத்தில் கண்காணிக்கப்பட்ட மரங்கள்',
      'healthy': 'ஆரோக்கியமான',
      'needAttention': 'கவனம் தேவை',
      'quickActions': 'விரைவான செயல்கள்',
      'scanLeaf': 'இலை ஸ்கேன் செய்',
      'takePhoto': 'ஒரு புகைப்படம் எடுக்கவும்',
      'droneReport': 'ড্রোন அறிக்கை',
      'uploadFootage': 'ফুটেஜ் আপলোড করুন',
      'scanHistory': 'ஸ্கேன் வரலாறு',
      'pastResults': 'கடந்த முடிவுகள்',
      'analytics': 'பகுப்பாய்வு',
      'diseaseTrends': 'நோய் போக்குகள்',
      'diseaseOverview': 'நோய் கண்ணோட்டம்',
      'thisMonth': 'இந்த மாதம்',
      'recentAlerts': 'சமீபத்திய எச்சரிக்கைகள்',
      'quickScan': 'விரைவு ஸ்கேன்',
      'settings': 'அமைப்புகள்',
      'notifications': 'அறிவிப்புகள்',
      'darkMode': 'இருண்ட முறை',
      'autoSync': 'தானியங்கி ஒத்திசைவு',
      'locationTracking': 'இருப்பிட ট்র্যাकிங்',
      'language': 'மொழி',
      'storageUsed': 'பயன்படுத்தப்பட்ட சேமிப்பகம்',
      'appVersion': 'பயன்பாட்டு பதிப்பு',
      'help': 'உதவி மற்றும் FAQ',
      'logout': 'வெளியேறு',
      'deleteAccount': '계정 삭제',
      'selectLanguage': 'மொழி தேர்ந்தெடுக்கவும்',
      'profileImageUpdated': 'சுயவிவரப் புகைப்படம் வெற்றிகரமாக பதிவேற்றப்பட்டது.',
      'failedToUploadImage': 'சுயவிவரப் புகைப்படத்தைப் பதிவேற்ற முடியவில்லை',
      'leafSpot': 'இலை புள்ளி',
      'lethalYellowing': 'முற்றிய மஞ்சள்',
      'budRot': 'மொட்ட腐',
      'confirmed': 'உறுதிப்படுத்தப்பட்டது',
      'uncertain': 'நிச்சயமற்ற',
      'seeAll': 'அனைத்தையும் பார்',
    },
  };

  static Future<void> initialize() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString(_languageKey) ?? 'English';
  }

  static Future<void> setLanguage(String language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language);
  }

  static String getCurrentLanguage() => _currentLanguage;

  static String translate(String key) {
    return _translations[_currentLanguage]?[key] ?? 
           _translations['English']?[key] ?? 
           key;
  }

  static String get(String key) => translate(key);

  static List<String> getAvailableLanguages() => _translations.keys.toList();
}
