// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn_z5coMjbTbHMb4INiuDyR29OWIcNQYE',
    appId: '1:334824669425:android:2b543ace4a3d410db5a950',
    messagingSenderId: '334824669425',
    projectId: 'cocoscan-app-9bccd',
    storageBucket: 'cocoscan-app-9bccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3gY0uZfp53mDQ_asHMbAH0xBkHY9RI0I',
    appId: '1:334824669425:ios:48ac01c114011ea6b5a950',
    messagingSenderId: '334824669425',
    projectId: 'cocoscan-app-9bccd',
    storageBucket: 'cocoscan-app-9bccd.firebasestorage.app',
    iosBundleId: 'com.example.cocoscan',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB-MkY7np6baO9NXlmIhfl0qnS7FRyuBQ',
    appId: '1:334824669425:web:f845093ff2748eaab5a950',
    messagingSenderId: '334824669425',
    projectId: 'cocoscan-app-9bccd',
    authDomain: 'cocoscan-app-9bccd.firebaseapp.com',
    storageBucket: 'cocoscan-app-9bccd.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3gY0uZfp53mDQ_asHMbAH0xBkHY9RI0I',
    appId: '1:334824669425:ios:48ac01c114011ea6b5a950',
    messagingSenderId: '334824669425',
    projectId: 'cocoscan-app-9bccd',
    storageBucket: 'cocoscan-app-9bccd.firebasestorage.app',
    iosBundleId: 'com.example.cocoscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB-MkY7np6baO9NXlmIhfl0qnS7FRyuBQ',
    appId: '1:334824669425:web:8b8ec8debe28763ab5a950',
    messagingSenderId: '334824669425',
    projectId: 'cocoscan-app-9bccd',
    authDomain: 'cocoscan-app-9bccd.firebaseapp.com',
    storageBucket: 'cocoscan-app-9bccd.firebasestorage.app',
  );

}